import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Nunito_Sans, Roboto } from 'next/font/google'
import '@/styles/globals.css'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
})
const NunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
  variable: '--font-nunito',
})

export const metadata: Metadata = {
  title: '16 Dias para Mudar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${NunitoSans.variable} ${roboto.className}`}>
        {children}
      </body>
    </html>
  )
}
